workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api|push|schedule$/
      when: always
    - when: never

stages:
  - build
  - test
  - deploy

variables:
  VAR1:
    description: "Variable 1"
    value: "value1"
  VAR2:
    description: "Variable 2"
    value: "value2"
  VAR3:
    description: "Variable 3"
    value: "value3"

build:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run build
