workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api|push|schedule$/
      when: always
    - when: never

stages:
  - build
  - test
  - deploy

variables:
  VAR1:
    value: "value1"
    description: "[value 1, value 2, value 3] - Variable 1, *Example: **value 1**, **value 2***"
  VAR2:
    value: "value2"
    description: "Variable 2, [link](https://www.google.com)"
  VAR3:
    value: "value3"
    description: "[text1, text2, text3] - Variable 3"
  DEPLOY_BRANCH:
    value: "main"
    description: "[$glBranches()] - Branch to deploy to"
  DEPLOY_BRANCH2:
    value: "main"
    description: "[$glBranches(42014162)] - Branch to deploy to"
  DEPLOY_BRANCH3:
    value: "main"
    description: "[$glBranches(42014162), inline-branch-1, inline-branch-2] - Branch to deploy to"
  EXTERNAL_VAR1:
    value: "external-value1"
    description: "External variable 1"
  EXTERNAL_VAR2:
    value: "external-value2"
    description: "External variable 2"

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
