workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api|push|schedule$/
      when: always
    - when: never

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run build
