workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api|push|schedule$/
      when: always
    - when: never

stages:
  - build
  - test
  - deploy

variables:
  VAR1:
    value: "value1"
    description: "[value 1, value 2, value 3] - Variable 1, *Example: **value 1**, **value 2***"
  VAR2:
    value: "value2"
    description: "Variable 2, [link](https://www.google.com)"
  VAR3:
    value: "value3"
    description: "[text1, text2, text3] - Variable 3"

build:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run build
